export const CREATE_EXPENSE_REQUEST = "CREATE_EXPENSE_REQUEST";
export const CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_FAIL = "CREATE_EXPENSE_FAIL";

export const UPDATE_EXPENSE_REQUEST = "UPDATE_EXPENSE_REQUEST";
export const UPDATE_EXPENSE_SUCCESS = "UPDATE_EXPENSE_SUCCESS";
export const UPDATE_EXPENSE_FAIL = "UPDATE_EXPENSE_FAIL";

export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAIL = "DELETE_EXPENSE_FAIL";

export const GET_EXPENSE_REQUEST = "GET_EXPENSE_REQUEST";
export const GET_EXPENSE_SUCCESS = "GET_EXPENSE_SUCCESS";
export const GET_EXPENSE_FAIL = "GET_EXPENSE_FAIL";

export const GET_EXPENSES_REQUEST = "GET_EXPENSES_REQUEST";
export const GET_EXPENSES_SUCCESS = "GET_EXPENSES_SUCCESS";
export const GET_EXPENSES_FAIL = "GET_EXPENSES_FAIL";

export const GET_EXPENSES_BY_ACCOUNT_REQUEST =
  "GET_EXPENSES_BY_ACCOUNT_REQUEST";
export const GET_EXPENSES_BY_ACCOUNT_SUCCESS =
  "GET_EXPENSES_BY_ACCOUNT_SUCCESS";
export const GET_EXPENSES_BY_ACCOUNT_FAIL = "GET_EXPENSES_BY_ACCOUNT_FAIL";

export const GET_EXPENSES_BY_MONTH_AND_YEAR_REQUEST =
  "GET_EXPENSES_BY_MONTH_AND_YEAR_REQUEST";
export const GET_EXPENSES_BY_MONTH_AND_YEAR_SUCCESS =
  "GET_EXPENSES_BY_MONTH_AND_YEAR_SUCCESS";
export const GET_EXPENSES_BY_MONTH_AND_YEAR_FAIL =
  "GET_EXPENSES_BY_MONTH_AND_YEAR_FAIL";
